//! Stepped synthetic sessions — the OptionChain-Simulator model folded into
//! `fauxchange` as **code, not a dependency**: deterministic chain synthesis
//! (`expirations × strikes` with a `smile_curve`-shaped volatility surface),
//! per-session generation parameters, and step-by-step advancement on the stepped
//! venue clock ([031](../../milestones/v0.3-replay/031-stepped-synthetic-sessions.md),
//! [04 §3](../../docs/04-market-data-and-replay.md#3-chain-synthesis-and-stepped-sessions),
//! [ADR-0001](../../docs/adr/0001-consolidate-option-chain-orderbook-backend.md)).
//!
//! The separate service is **retired**: no ClickHouse / Redis / MongoDB stack and
//! no `/api/v1/chain` session-lifecycle REST surface come with it — chains already
//! live in the consolidated REST hierarchy. What is absorbed is the *idea*:
//!
//! - **Per-session generation parameters** ([`SessionConfig`]) — initial price,
//!   days-to-expiration, volatility, risk-free rate, dividend yield, walk method,
//!   strike interval, chain size, `smile_curve` (+ `skew_slope`), and `spread` —
//!   shape a synthetic chain per scenario.
//! - **Chain synthesis** ([`synthesize_chain`]) — materialise the
//!   `expirations × strikes` instrument grid deterministically, with the per-strike
//!   implied volatility shaped by the smile **through `optionstratlib`**
//!   ([`optionstratlib::chains::utils::adjust_volatility`], never a hand-rolled
//!   volatility surface): `σ(K) = σ_atm · clamp(1 + skew·m + smile·m²)`,
//!   `m = ln(K/S)`, so a positive `smile_curve` raises the wing IVs (the classic
//!   volatility smile).
//! - **Stepped advancement** — a session step advances the venue clock by the fixed
//!   virtual interval and walks the underlying one price step; both enter the
//!   sequencer as journaled `Clock` / `SimStep` commands, and the market maker's
//!   derived requotes are themselves journaled `AddOrder`s. Replay reproduces the
//!   session from the journal with the live requote engine muted (#030) — the
//!   application wiring (`AppState::materialize_session` / `AppState::step_session`)
//!   composes this domain synthesis with the #016 simulator + #028 clock + #015
//!   market maker.
//!
//! ## Determinism, scoped honestly (rule 5)
//!
//! The chain **synthesis** (the strike grid, the smile-shaped IVs, the DateTime
//! expiry, the instrument set) is a **pure deterministic function of the
//! [`SessionConfig`]** — no clock, no RNG — so the same config yields the identical
//! chain every time. The stepped **price path**, however, is generated by the
//! `optionstratlib` walk sampler, which builds its **own** `rand::rng()` per draw
//! and cannot consume the run seed
//! ([04 §2](../../docs/04-market-data-and-replay.md#2-synthetic-price-generation)):
//! the guaranteed reproduction of the *path* is the **journal** (replay
//! re-executes the recorded `SimStep`s), **not** seed-regeneration. So "a stepped
//! session advances identically for the same seed" holds precisely as: **identical
//! deterministic synthesis** for the same config, and **journal-driven** identical
//! replay of the stochastic price path — never a claim of a seed-regenerated price
//! path.
//!
//! ## Replay-stable expiries (rule / #032)
//!
//! Every synthesised expiry is an absolute [`ExpirationDate::DateTime`], derived by
//! **pure civil-date arithmetic** from a fixed base instant plus `days_to_expiration`
//! (never `Utc::now()`, never a `Days`-relative expiry), so a stepped session is
//! replay-stable.

use optionstratlib::chains::utils::adjust_volatility;
use optionstratlib::prelude::{Decimal, Positive};
use serde::{Deserialize, Serialize};

use crate::exchange::{Cents, ExpirationDate, OptionStyle, Symbol, SymbolParser};
use crate::simulation::simulator::AssetConfig;
use crate::simulation::walk::{SimError, WalkTypeConfig};

/// Milliseconds in a UTC day — the civil-date arithmetic basis (fixed, never a
/// wall-clock read).
const MILLIS_PER_DAY: u64 = 24 * 60 * 60 * 1_000;

/// The default number of strikes in a synthesised chain (an odd count so the ATM
/// strike is centred).
pub const DEFAULT_CHAIN_SIZE: usize = 11;

/// The default per-session `smile_curve` (`0.0` — a flat surface until a scenario
/// shapes it).
pub const DEFAULT_SMILE_CURVE: f64 = 0.0;

/// The default per-session `skew_slope` (`0.0` — no tilt).
pub const DEFAULT_SKEW_SLOPE: f64 = 0.0;

/// The default per-session chain `spread` fraction (`2%`).
pub const DEFAULT_SPREAD: f64 = 0.02;

/// The default per-session dividend yield (`0%`).
pub const DEFAULT_DIVIDEND_YIELD: f64 = 0.0;

/// The default risk-free rate (`5%`), matching the market-maker pricer default.
pub const DEFAULT_RISK_FREE_RATE: f64 = 0.05;

/// The fraction of spot the default strike interval targets (`1%` of spot),
/// floored at `1` whole unit — a sensible grid step across price scales.
const DEFAULT_STRIKE_INTERVAL_FRACTION: f64 = 0.01;

// ============================================================================
// SessionConfig — the per-session generation parameters
// ============================================================================

/// The per-session generation parameters that shape a synthetic chain per scenario
/// ([04 §3](../../docs/04-market-data-and-replay.md#3-chain-synthesis-and-stepped-sessions)).
///
/// Serde with `deny_unknown_fields` so it is config-surface-ready (a stray field is
/// a hard decode error, never a silent typo). Money is integer [`Cents`]; the model
/// floats (`volatility`, `smile_curve`, …) are the documented analytic exception.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionConfig {
    /// The underlying ticker the session drives (e.g. `"BTC"`).
    pub underlying: String,
    /// The opening / initial underlying price, in **cents**.
    pub initial_price: Cents,
    /// Days to expiration for the synthesised expiry (`> 0`).
    pub days_to_expiration: f64,
    /// The at-the-money base implied volatility (`> 0`, e.g. `0.20` for 20%).
    pub volatility: f64,
    /// The annualised risk-free rate (e.g. `0.05`).
    pub risk_free_rate: f64,
    /// The dividend yield (`>= 0`).
    pub dividend_yield: f64,
    /// The price-walk method, routed through [`WalkTypeConfig`] →
    /// `optionstratlib::WalkType`.
    pub walk_type: WalkTypeConfig,
    /// The gap between adjacent strikes, in **whole units** (`>= 1`).
    pub strike_interval: u64,
    /// The number of strikes to materialise (`>= 1`).
    pub chain_size: usize,
    /// The volatility-smile **curvature** term (`smile_curve`): `> 0` raises the
    /// wings (a smile), `< 0` lowers them, `0` is flat.
    pub smile_curve: f64,
    /// The volatility-smile **skew** term (slope per unit log-moneyness): tilts the
    /// surface. `0` is symmetric.
    pub skew_slope: f64,
    /// The chain spread fraction (`> 0`) — a **recorded scenario parameter** that
    /// shapes the synthesised chain's nominal bid/ask width. Note the venue seeds
    /// live liquidity through the **market maker** (whose two-sided quote spread is
    /// its own `base_spread_bps`), so this value is carried as part of the
    /// reproducible session descriptor rather than driving the sequenced quotes; a
    /// per-session MM spread is a documented seam (like the per-underlying persona
    /// knobs), deferred to the microstructure work (v0.5).
    pub spread: f64,
}

impl SessionConfig {
    /// Builds a session config with the grid / smile / rate parameters defaulted,
    /// deriving a `1%`-of-spot strike interval. Override the rest with the
    /// `with_*` setters.
    #[must_use]
    pub fn new(
        underlying: impl Into<String>,
        initial_price: Cents,
        days_to_expiration: f64,
        volatility: f64,
        walk_type: WalkTypeConfig,
    ) -> Self {
        let strike_interval = default_strike_interval(initial_price);
        Self {
            underlying: underlying.into(),
            initial_price,
            days_to_expiration,
            volatility,
            risk_free_rate: DEFAULT_RISK_FREE_RATE,
            dividend_yield: DEFAULT_DIVIDEND_YIELD,
            walk_type,
            strike_interval,
            chain_size: DEFAULT_CHAIN_SIZE,
            smile_curve: DEFAULT_SMILE_CURVE,
            skew_slope: DEFAULT_SKEW_SLOPE,
            spread: DEFAULT_SPREAD,
        }
    }

    /// Sets the strike interval (whole units).
    #[must_use]
    pub fn with_strike_interval(mut self, strike_interval: u64) -> Self {
        self.strike_interval = strike_interval;
        self
    }

    /// Sets the number of strikes to materialise.
    #[must_use]
    pub fn with_chain_size(mut self, chain_size: usize) -> Self {
        self.chain_size = chain_size;
        self
    }

    /// Sets the smile curvature term.
    #[must_use]
    pub fn with_smile_curve(mut self, smile_curve: f64) -> Self {
        self.smile_curve = smile_curve;
        self
    }

    /// Sets the smile skew slope.
    #[must_use]
    pub fn with_skew_slope(mut self, skew_slope: f64) -> Self {
        self.skew_slope = skew_slope;
        self
    }

    /// Sets the risk-free rate.
    #[must_use]
    pub fn with_risk_free_rate(mut self, risk_free_rate: f64) -> Self {
        self.risk_free_rate = risk_free_rate;
        self
    }

    /// Sets the dividend yield.
    #[must_use]
    pub fn with_dividend_yield(mut self, dividend_yield: f64) -> Self {
        self.dividend_yield = dividend_yield;
        self
    }

    /// Sets the chain spread fraction.
    #[must_use]
    pub fn with_spread(mut self, spread: f64) -> Self {
        self.spread = spread;
        self
    }

    /// Validates the session parameters at the `f64` boundary before synthesis.
    ///
    /// # Errors
    ///
    /// [`SimError::InvalidParameter`] naming the offending parameter if any value
    /// is non-finite or out of its documented range.
    pub fn validate(&self) -> Result<(), SimError> {
        if self.underlying.trim().is_empty() {
            return Err(SimError::InvalidParameter(
                "underlying must not be empty".into(),
            ));
        }
        if self.initial_price.get() == 0 {
            return Err(SimError::InvalidParameter(
                "initial_price must be > 0".into(),
            ));
        }
        require_finite_positive("days_to_expiration", self.days_to_expiration)?;
        require_finite_positive("volatility", self.volatility)?;
        require_finite("risk_free_rate", self.risk_free_rate)?;
        require_finite_nonneg("dividend_yield", self.dividend_yield)?;
        require_finite("smile_curve", self.smile_curve)?;
        require_finite("skew_slope", self.skew_slope)?;
        require_finite_positive("spread", self.spread)?;
        if self.strike_interval == 0 {
            return Err(SimError::InvalidParameter(
                "strike_interval must be >= 1".into(),
            ));
        }
        if self.chain_size == 0 {
            return Err(SimError::InvalidParameter("chain_size must be >= 1".into()));
        }
        Ok(())
    }

    /// The [`AssetConfig`] the session's underlying is hosted as on the price
    /// simulator (the walk seam the stepped path advances). The drift is `0.0`
    /// (the session shapes the level, not a directional drift).
    #[must_use]
    pub fn to_asset_config(&self) -> AssetConfig {
        AssetConfig::new(
            self.underlying.clone(),
            self.initial_price,
            self.volatility,
            self.walk_type,
        )
    }
}

/// The default strike interval: `~1%` of spot in whole units, floored at `1`.
fn default_strike_interval(initial_price: Cents) -> u64 {
    let spot_dollars = initial_price.get() as f64 / 100.0;
    let interval = (spot_dollars * DEFAULT_STRIKE_INTERVAL_FRACTION).round();
    if interval.is_finite() && interval >= 1.0 {
        interval as u64
    } else {
        1
    }
}

// ============================================================================
// The synthesised chain
// ============================================================================

/// One synthesised strike: its whole-unit strike, the call/put contract symbols,
/// and the `smile_curve`-shaped implied volatility (one IV per strike, shared by the
/// call and put leg).
#[derive(Debug, Clone, PartialEq)]
pub struct SynthesizedStrike {
    /// The strike in **whole units**.
    pub strike: u64,
    /// The canonical call contract symbol.
    pub call: Symbol,
    /// The canonical put contract symbol.
    pub put: Symbol,
    /// The smile-shaped implied volatility at this strike (from `optionstratlib`).
    pub iv: f64,
}

/// A deterministically synthesised option chain — the `expirations × strikes`
/// instrument grid for one session, at one absolute [`ExpirationDate::DateTime`]
/// expiry, with per-strike smile IVs.
#[derive(Debug, Clone, PartialEq)]
pub struct SynthesizedChain {
    /// The underlying ticker.
    pub underlying: String,
    /// The absolute (canonical `DateTime`) expiry every contract is keyed on.
    pub expiration: ExpirationDate,
    /// The opening underlying price, in **cents**.
    pub spot: Cents,
    /// The materialised strikes, in ascending strike order.
    pub strikes: Vec<SynthesizedStrike>,
}

impl SynthesizedChain {
    /// The `(symbol, iv)` pairs for every leg (call then put per strike, ascending)
    /// — the instrument set to register with the market maker so each leaf is
    /// seeded with a smile-shaped quote.
    #[must_use]
    pub fn instruments(&self) -> Vec<(Symbol, f64)> {
        let mut out = Vec::with_capacity(self.strikes.len() * 2);
        for strike in &self.strikes {
            out.push((strike.call.clone(), strike.iv));
            out.push((strike.put.clone(), strike.iv));
        }
        out
    }

    /// The number of contracts materialised (two per strike).
    #[must_use]
    pub fn contract_count(&self) -> usize {
        self.strikes.len() * 2
    }
}

// ============================================================================
// Chain synthesis
// ============================================================================

/// Synthesises the instrument grid for `config`, with the per-strike implied
/// volatility shaped by the smile **through `optionstratlib`**.
///
/// The expiry is an absolute [`ExpirationDate::DateTime`] `config.days_to_expiration`
/// days after `base_now_ms` (pure civil-date arithmetic — replay-stable, never
/// `Utc::now()`). The strike grid is `config.chain_size` whole-unit strikes centred
/// on the ATM strike at `config.strike_interval`; each strike's IV is
/// [`optionstratlib::chains::utils::adjust_volatility`] evaluated at that strike, so
/// the smile is optionstratlib's, not a local surface.
///
/// A pure deterministic function of `(config, base_now_ms)` — no clock, no RNG.
///
/// # Errors
///
/// - [`SimError::InvalidParameter`] if a parameter is out of range (via
///   [`SessionConfig::validate`]) or the spot / a strike / an IV is non-finite;
/// - [`SimError::ChainSynthesisFailed`] if the expiry cannot be resolved or a
///   contract symbol cannot be minted through the upstream grammar.
#[must_use = "the synthesised chain is the session's instrument set"]
pub fn synthesize_chain(
    config: &SessionConfig,
    base_now_ms: u64,
) -> Result<SynthesizedChain, SimError> {
    config.validate()?;

    let spot_dollars = config.initial_price.get() as f64 / 100.0;
    if !(spot_dollars.is_finite() && spot_dollars > 0.0) {
        return Err(SimError::InvalidParameter(format!(
            "spot is not finite and positive: {spot_dollars}"
        )));
    }
    let spot_positive = positive("spot", spot_dollars)?;
    let base_vol = positive("volatility", config.volatility)?;
    let skew = decimal("skew_slope", config.skew_slope)?;
    let smile = decimal("smile_curve", config.smile_curve)?;

    // The absolute, canonical `DateTime` expiry: base civil date + days_to_expiration.
    let yyyymmdd = expiry_yyyymmdd(base_now_ms, config.days_to_expiration)?;
    let expiration = SymbolParser::parse_yyyymmdd(&yyyymmdd, "").map_err(|error| {
        SimError::ChainSynthesisFailed(format!("expiry {yyyymmdd} unresolvable: {error}"))
    })?;

    // The ATM strike snaps the spot onto the strike grid; strikes fan out
    // symmetrically at `strike_interval`.
    let interval = config.strike_interval;
    // Checked arithmetic throughout (money-adjacent values, rule 9): a
    // pathological `initial_price` / `strike_interval` combination is a typed
    // `InvalidParameter`, never a silent wrap or saturation.
    let interval_signed = i64::try_from(interval).map_err(|_| {
        SimError::InvalidParameter("strike interval exceeds the signed strike range".into())
    })?;
    let atm = {
        let steps = (spot_dollars / interval as f64).round();
        // The upper bound keeps the f64 → u64 cast exact (no float saturation).
        if !(steps.is_finite() && steps >= 1.0 && steps <= u32::MAX as f64) {
            return Err(SimError::InvalidParameter(
                "spot is out of range for the strike interval".into(),
            ));
        }
        (steps as u64).checked_mul(interval).ok_or_else(|| {
            SimError::InvalidParameter("strike grid overflows: spot x interval too large".into())
        })?
    };
    let atm_signed = i64::try_from(atm).map_err(|_| {
        SimError::InvalidParameter("ATM strike exceeds the signed strike range".into())
    })?;
    let half = (config.chain_size / 2) as i64;

    let mut strikes = Vec::with_capacity(config.chain_size);
    for i in 0..config.chain_size as i64 {
        let strike_signed = i
            .checked_sub(half)
            .and_then(|steps| steps.checked_mul(interval_signed))
            .and_then(|offset| atm_signed.checked_add(offset))
            .ok_or_else(|| {
                SimError::InvalidParameter(
                    "strike grid overflows: chain size x interval too large".into(),
                )
            })?;
        if strike_signed <= 0 {
            continue; // a non-positive strike is not a valid contract; skip it
        }
        let strike = strike_signed as u64;
        let strike_positive = positive("strike", strike as f64)?;

        // The smile-shaped IV at this strike — optionstratlib's surface, not ours.
        let iv = adjust_volatility(
            &Some(base_vol),
            &Some(skew),
            &Some(smile),
            &strike_positive,
            &spot_positive,
        )
        .map(|vol| vol.to_f64())
        .filter(|iv| iv.is_finite() && *iv > 0.0)
        .ok_or_else(|| {
            SimError::InvalidParameter(format!("smile produced a non-finite IV at strike {strike}"))
        })?;

        let call = contract_symbol(&config.underlying, &yyyymmdd, strike, OptionStyle::Call)?;
        let put = contract_symbol(&config.underlying, &yyyymmdd, strike, OptionStyle::Put)?;
        strikes.push(SynthesizedStrike {
            strike,
            call,
            put,
            iv,
        });
    }

    if strikes.is_empty() {
        return Err(SimError::ChainSynthesisFailed(
            "no positive strikes were materialised".into(),
        ));
    }

    Ok(SynthesizedChain {
        underlying: config.underlying.clone(),
        expiration,
        spot: config.initial_price,
        strikes,
    })
}

/// Builds a canonical venue contract [`Symbol`] through the upstream grammar.
fn contract_symbol(
    underlying: &str,
    yyyymmdd: &str,
    strike: u64,
    style: OptionStyle,
) -> Result<Symbol, SimError> {
    let style_char = match style {
        OptionStyle::Call => 'C',
        OptionStyle::Put => 'P',
    };
    let raw = format!("{underlying}-{yyyymmdd}-{strike}-{style_char}");
    Symbol::parse(&raw)
        .map_err(|error| SimError::ChainSynthesisFailed(format!("symbol {raw} invalid: {error}")))
}

/// The `YYYYMMDD` of the expiry: the civil date `days_to_expiration` days after the
/// civil date of `base_now_ms`, by pure integer arithmetic (never `Utc::now()`).
fn expiry_yyyymmdd(base_now_ms: u64, days_to_expiration: f64) -> Result<String, SimError> {
    if !(days_to_expiration.is_finite() && days_to_expiration > 0.0) {
        return Err(SimError::InvalidParameter(format!(
            "days_to_expiration must be finite and positive, got {days_to_expiration}"
        )));
    }
    let base_days = (base_now_ms / MILLIS_PER_DAY) as i64;
    let expiry_days = base_days
        .checked_add(days_to_expiration.round() as i64)
        .ok_or_else(|| SimError::InvalidParameter("expiry day count overflow".into()))?;
    let (year, month, day) = civil_from_days(expiry_days);
    Ok(format!("{year:04}{month:02}{day:02}"))
}

/// Converts a day count since the Unix epoch (1970-01-01) to a `(year, month,
/// day)` civil date — Howard Hinnant's algorithm, pure integer arithmetic, no
/// dependency and no wall-clock read.
fn civil_from_days(z: i64) -> (i64, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097; // [0, 146096]
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365; // [0, 399]
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32; // [1, 31]
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32; // [1, 12]
    (if m <= 2 { y + 1 } else { y }, m, d)
}

// ---- f64-boundary guards ----------------------------------------------------

/// Builds a strictly-positive `optionstratlib` [`Positive`] from `value`, naming
/// the parameter on failure.
fn positive(name: &str, value: f64) -> Result<Positive, SimError> {
    if !(value.is_finite() && value > 0.0) {
        return Err(SimError::InvalidParameter(format!(
            "{name} must be finite and positive, got {value}"
        )));
    }
    Positive::new(value).map_err(|error| SimError::InvalidParameter(format!("{name}: {error}")))
}

/// Builds an `optionstratlib` [`Decimal`] from `value`, naming the parameter on a
/// non-finite input.
fn decimal(name: &str, value: f64) -> Result<Decimal, SimError> {
    Decimal::from_f64_retain(value).ok_or_else(|| {
        SimError::InvalidParameter(format!("{name} is not a finite decimal: {value}"))
    })
}

/// Requires a finite value.
fn require_finite(name: &str, value: f64) -> Result<(), SimError> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(SimError::InvalidParameter(format!(
            "{name} must be finite, got {value}"
        )))
    }
}

/// Requires a finite, strictly-positive value.
fn require_finite_positive(name: &str, value: f64) -> Result<(), SimError> {
    if value.is_finite() && value > 0.0 {
        Ok(())
    } else {
        Err(SimError::InvalidParameter(format!(
            "{name} must be finite and positive, got {value}"
        )))
    }
}

/// Requires a finite, non-negative value.
fn require_finite_nonneg(name: &str, value: f64) -> Result<(), SimError> {
    if value.is_finite() && value >= 0.0 {
        Ok(())
    } else {
        Err(SimError::InvalidParameter(format!(
            "{name} must be finite and non-negative, got {value}"
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The deterministic base instant (2025-01-01T00:00:00Z, in ms) — matches the
    /// venue clock's default virtual epoch.
    const BASE_MS: u64 = 1_735_689_600_000;

    fn base_config() -> SessionConfig {
        SessionConfig::new(
            "BTC",
            Cents::new(5_000_000), // $50,000
            30.0,
            0.20,
            WalkTypeConfig::GeometricBrownian,
        )
        .with_strike_interval(500)
        .with_chain_size(11)
    }

    #[test]
    fn test_chain_synthesis_materialises_grid() {
        let config = base_config();
        let chain = synthesize_chain(&config, BASE_MS).expect("a well-posed session synthesises");

        // chain_size strikes, two contracts each, ascending, centred on the ATM
        // strike (50000), at the 500 interval.
        assert_eq!(chain.strikes.len(), 11, "chain_size strikes materialised");
        assert_eq!(chain.contract_count(), 22, "call + put per strike");
        let strikes: Vec<u64> = chain.strikes.iter().map(|s| s.strike).collect();
        assert_eq!(strikes.first(), Some(&(50_000 - 5 * 500)));
        assert_eq!(strikes.last(), Some(&(50_000 + 5 * 500)));
        assert!(
            strikes.windows(2).all(|w| w[1] == w[0] + 500),
            "strikes step by the interval, ascending"
        );
        // Contracts carry the ATM strike and the DateTime expiry.
        let atm = chain
            .strikes
            .iter()
            .find(|s| s.strike == 50_000)
            .expect("an ATM strike");
        assert_eq!(atm.call.as_str(), "BTC-20250131-50000-C");
        assert_eq!(atm.put.as_str(), "BTC-20250131-50000-P");
    }

    #[test]
    fn test_every_synthesised_expiry_is_datetime() {
        let chain = synthesize_chain(&base_config(), BASE_MS).expect("synthesise");
        assert!(
            matches!(chain.expiration, ExpirationDate::DateTime(_)),
            "a synthesised expiry must be an absolute DateTime (replay-stable)"
        );
    }

    #[test]
    fn test_smile_curve_shapes_smile() {
        // A positive smile_curve raises the wing IVs above the ATM base vol (the
        // classic volatility smile), computed through optionstratlib.
        let config = base_config().with_smile_curve(0.5).with_skew_slope(0.0);
        let chain = synthesize_chain(&config, BASE_MS).expect("synthesise");

        let atm = chain
            .strikes
            .iter()
            .find(|s| s.strike == 50_000)
            .expect("ATM");
        let low_wing = chain.strikes.first().expect("low wing");
        let high_wing = chain.strikes.last().expect("high wing");

        // ATM IV is ~ the base vol; the wings are strictly higher.
        assert!(
            (atm.iv - 0.20).abs() < 1e-6,
            "ATM IV equals the base vol, got {}",
            atm.iv
        );
        assert!(
            low_wing.iv > atm.iv,
            "the low wing IV ({}) exceeds ATM ({}) under a positive smile",
            low_wing.iv,
            atm.iv
        );
        assert!(
            high_wing.iv > atm.iv,
            "the high wing IV ({}) exceeds ATM ({}) under a positive smile",
            high_wing.iv,
            atm.iv
        );

        // A larger smile_curve raises the wing further (monotone in the curvature).
        let steeper =
            synthesize_chain(&base_config().with_smile_curve(1.5), BASE_MS).expect("synthesise");
        let steeper_wing = steeper.strikes.last().expect("high wing");
        assert!(
            steeper_wing.iv > high_wing.iv,
            "a steeper smile_curve raises the wing IV: {} !> {}",
            steeper_wing.iv,
            high_wing.iv
        );
    }

    #[test]
    fn test_zero_smile_is_flat() {
        let chain = synthesize_chain(
            &base_config().with_smile_curve(0.0).with_skew_slope(0.0),
            BASE_MS,
        )
        .expect("synthesise");
        // A flat surface: every strike carries the base vol.
        assert!(
            chain.strikes.iter().all(|s| (s.iv - 0.20).abs() < 1e-6),
            "a zero smile/skew is a flat vol surface"
        );
    }

    #[test]
    fn test_synthesis_is_deterministic_for_the_same_config() {
        // The chain synthesis is a pure function of (config, base) — no clock, no
        // RNG — so two calls produce the byte-identical chain (the deterministic
        // half of the same-seed acceptance line; the stochastic price path is
        // reproduced from the journal, not regenerated here).
        let config = base_config().with_smile_curve(0.7).with_skew_slope(-0.2);
        let a = synthesize_chain(&config, BASE_MS).expect("synthesise a");
        let b = synthesize_chain(&config, BASE_MS).expect("synthesise b");
        assert_eq!(a, b, "the same config synthesises the identical chain");
    }

    #[test]
    fn test_skew_slope_tilts_the_surface() {
        // A negative skew_slope raises the low wing above the high wing (a
        // put/downside skew) — the surface is asymmetric.
        let chain = synthesize_chain(
            &base_config().with_smile_curve(0.3).with_skew_slope(-0.5),
            BASE_MS,
        )
        .expect("synthesise");
        let low = chain.strikes.first().expect("low");
        let high = chain.strikes.last().expect("high");
        assert!(
            low.iv > high.iv,
            "a negative skew tilts IV toward the downside: low {} !> high {}",
            low.iv,
            high.iv
        );
    }

    #[test]
    fn test_validate_rejects_degenerate_parameters() {
        let ok = base_config();
        assert!(ok.validate().is_ok());
        for bad in [
            SessionConfig {
                volatility: 0.0,
                ..ok.clone()
            },
            SessionConfig {
                volatility: f64::NAN,
                ..ok.clone()
            },
            SessionConfig {
                days_to_expiration: 0.0,
                ..ok.clone()
            },
            SessionConfig {
                days_to_expiration: -1.0,
                ..ok.clone()
            },
            SessionConfig {
                chain_size: 0,
                ..ok.clone()
            },
            SessionConfig {
                strike_interval: 0,
                ..ok.clone()
            },
            SessionConfig {
                smile_curve: f64::INFINITY,
                ..ok.clone()
            },
            SessionConfig {
                spread: 0.0,
                ..ok.clone()
            },
            SessionConfig {
                initial_price: Cents::new(0),
                ..ok.clone()
            },
        ] {
            assert!(
                bad.validate().is_err(),
                "a degenerate config must be rejected: {bad:?}"
            );
            // And synthesis fails safe (a typed error, never a panic / poisoned chain).
            assert!(synthesize_chain(&bad, BASE_MS).is_err());
        }
    }

    #[test]
    fn test_config_serde_rejects_unknown_field() {
        let json = r#"{"underlying":"BTC","initial_price":5000000,"days_to_expiration":30.0,"volatility":0.2,"risk_free_rate":0.05,"dividend_yield":0.0,"walk_type":"GeometricBrownian","strike_interval":500,"chain_size":11,"smile_curve":0.0,"skew_slope":0.0,"spread":0.02,"typo":true}"#;
        assert!(
            serde_json::from_str::<SessionConfig>(json).is_err(),
            "an unknown field must be a hard decode error"
        );
    }

    #[test]
    fn test_config_serde_roundtrips() {
        let config = base_config().with_smile_curve(0.4);
        let json = serde_json::to_string(&config).expect("serialize");
        let back: SessionConfig = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, config);
    }

    #[test]
    fn test_to_asset_config_maps_the_walk_seam() {
        let config = base_config();
        let asset = config.to_asset_config();
        assert_eq!(asset.underlying, "BTC");
        assert_eq!(asset.initial_price, Cents::new(5_000_000));
        assert_eq!(asset.walk_type, WalkTypeConfig::GeometricBrownian);
    }

    #[test]
    fn test_civil_from_days_matches_known_dates() {
        // 2025-01-01 is 20089 days after the Unix epoch.
        assert_eq!(civil_from_days(20_089), (2025, 1, 1));
        // The epoch itself.
        assert_eq!(civil_from_days(0), (1970, 1, 1));
        // A leap day.
        assert_eq!(civil_from_days(civil_days(2024, 2, 29)), (2024, 2, 29));
    }

    /// Test helper: days since the epoch for a civil date (inverse of
    /// `civil_from_days`), for the leap-day assertion.
    fn civil_days(y: i64, m: u32, d: u32) -> i64 {
        let y = if m <= 2 { y - 1 } else { y };
        let era = if y >= 0 { y } else { y - 399 } / 400;
        let yoe = y - era * 400;
        let mp = (if m > 2 { m - 3 } else { m + 9 }) as i64;
        let doy = (153 * mp + 2) / 5 + d as i64 - 1;
        let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
        era * 146_097 + doe - 719_468
    }
}
